export const errors = {
  ACCESS_DENIED: "Access Denied for this user",
  CONNECTION_ERROR: "Unable to connect to the database: ",
  UNAUTHORIZED: "Token expired or Unauthorized",
  NO_TOKEN: "There is no token attached to the header!",
  USER_EXIST: "User already exists",
  OTP_FAILED: "Invalid Otp",
  USER_NOT: "User not found",
  INVALID_CODE: "Invalid Code",
  INVALID_PASSWORD: "Invalid Password",
  ALREADY_USED: "Already Used",
  ACCOUNT_BLOCK: "Your account has been blocked",
  NOT_FOUND: "Data not found",
  ID_NOT_FOUND: "ID not found",
  FORMAT_ERROR: "Unsupported file format",
  BANK_ERROR: "Please update your Bank Details",
  BALANCE_ERROR: "You don't have sufficient balance to withdraw",
};

export const message = {
  CONNECTION_SUCCESS: "Connection has been established successfully",
  REGISTERATION_SUCCESS: "Registration Successful",
  OTP_SENT: "OTP send Successfully",
  OTP_VERIFY: "OTP verified Successfully",
  LOGIN_SUCCESS: "Login Successful",
  USER_DELETE: "Account Deleted",
  USER_BLOCK: "Account Blocked",
  USER_UNBLOCK: "Account Unblocked",
  DATA_UPDATE: "Data update successfully",
  DATA_SUCCESS: "Data fetched successfully",
  PASSWORD_UPDATE: "Password updated successfully",
  DATA_CREATE: "Data created successfully",
  DATA_DELETE: "Data deleted successfully",
  REFERRAL_APPLIED: "Code Applied",
  USER_IMPORT: "User data imported",
  PAYOUT_SUCCESS: "Payout Success",
  MESSAGE_READ: "All Readed",
};
